### ISSUE TITLE
Resolve Player movement conflicts

### ISSUE THREAD

**Issue by nchaika1000** [NikitaVr/the-seed-server#2]
# Description 

# Stories
- [ ] Detect Player Movement Conflict https://github.com/NikitaVr/the-seed-server/issues/3
- [ ] Do not allow multiple players movement into the same cell https://github.com/NikitaVr/the-seed-server/issues/4
- [ ] Sent notification to players about movement conflict #5
